run:
  deadline: 10m
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - deadcode
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

  # disable problem linters
  disable:
    - errcheck         # generally reports false positives and is invasive
    - gochecknoglobals # version
    - maligned         # no guarantee per compiler version

